### ISSUE TITLE
Mouse click event error

### ISSUE THREAD

**Issue by matthewcare** [dapplo/Dapplo.Windows#19]
I couldn't get the `MouseClick` event to work properly, digging into the code

https://github.com/dapplo/Dapplo.Windows/blob/c3ece8900ba8def6a4af5e02d58af6cead92d122/src/Dapplo.Windows.Input/Mouse/MouseInputGenerator.cs#L23

it looks like an error whereby the `MouseDown` event is fired twice, rather than a `MouseDown` and a `MouseUp`.

**Comment by Lakritzator** [comment]
It looks like you are right, probably a copy / paste error and while I never used it, it didn't show.
I'll fix it, and let you know in what version this comes.

**Comment by Lakritzator** [comment]
Should be fixed with 1.0.27
